### ISSUE TITLE
お茶の時間

### ISSUE THREAD

**Issue by Muratam** [kmc-jp/choujinroku#15]
イベント判定の「お茶の時間を楽しんだ。同じマスに他のPCが居たら、その場に居る全員の残機が1増え、手番はここで終了。」は、お茶の時間を楽しんだ主体がターンプレイヤーでない場合かつターンプレイヤーも同じマスにいた場合、ターンプレイヤーも巻き添えで手番終了な気がする(そんなこと発生する？？？？？？？？ )

**Comment by suzusime** [comment]
>お茶の時間を楽しんだ主体がターンプレイヤーでない場合かつターンプレイヤーも同じマスにいた場合、ターンプレイヤーも巻き添えで手番終了な気がする

はたしかにそうなりそうですけど、ターンプレイヤー以外がイベント判定することってあるんですか？
