### ISSUE TITLE
doc/readme.mdのリンク

### ISSUE THREAD

**Issue by suzusime** [kmc-jp/choujinroku#42]
doc/readme.mdからのリンクってなんで ./doc/hoge.md の形になっているんでしょう？
（これだとGitHubやVSCodeのプレビューではリンク切れになる）（この指定の方が良い環境があるんでしょうか？）

**Comment by nonylene** [comment]
https://github.com/kmc-jp/choujinroku/commit/75ac47756f355fff9491c99916d498c06a47529c#diff-9a09b4dfda82e3e665e31092d1c3ec8d この commit によってディレクトリ構造が変わりリンク切れになった？

**Comment by Muratam** [comment]
ディレクトリ構造変わってそう、というかドキュメントはatwikiの方をメインにしたいから doc/ 以下不要だな
