### ISSUE TITLE
「無作為に」はダイス反転可能？？ 

### ISSUE THREAD

**Issue by Muratam** [kmc-jp/choujinroku#6]
「宴会で飲みすぎて前後不覚になり戦闘履歴が無作為に一人分初期化される」をダイス反転できてほしくないから多分ダイス反転は無理(でも振り直しは可能？？？ )

**Comment by Muratam** [comment]
振り直しも不可能では？？？？？？

**Comment by kebus426** [comment]
「無作為に」を実際に行う際にサイコロを使っているだけでゲーム内の処理としてサイコロを振っているわけではないのでは？
